Couple of small fixes to the body
Jasius/dotsimusApp pull request #2
Opened 2021-04-28 12:39 UTC by heftymouse

Changed body margins, removed gradient (it looked out of place to me), made Dotsimus top bar text larger, added fancy invite and premium buttons (idrk about this, might remove it later)

2021-04-28 12:44 UTC, heftymouse commented
Also I hid the Dotsimus text on mobile, I'll replace it with just the logo later

2021-05-01 16:44 UTC, Jasius requested changes
Thank you for the changes, there's just one issue that I've noticed other than that I like the changes!

2021-05-01 16:44 UTC, Jasius commented on src/index.js
> +                    <div class="hidden lg:block lg:flex-grow pl-5 t-2 text-xl text-black font-bold title-font text-base">Dotsimus</div>
It seems that there's a slight height misalignment since the addition of the avatar. 
![image](https://user-images.githubusercontent.com/11031051/116788988-434f3900-aab5-11eb-81d9-d32f2ea770f1.png)

2021-05-02 08:00 UTC, heftymouse commented on src/index.js
> +                    <div class="hidden lg:block lg:flex-grow pl-5 t-2 text-xl text-black font-bold title-font text-base">Dotsimus</div>
Fixed!

2021-05-02 08:22 UTC, heftymouse commented on src/index.js
> +                    <div class="hidden lg:block lg:flex-grow pl-5 t-2 text-xl text-black font-bold title-font text-base">Dotsimus</div>
It's a pretty hacky fix though, it seems to be having issues with the `xl` text size so I just added some extra padding on top

2021-05-02 12:30 UTC, Jasius approved these changes
Thank you once again for your help!!

2021-05-02 12:30 UTC, merged